%ifndef INPUT_INC
%define INPUT_INC

%define VK_LBUTTON  0x01
%define VK_RBUTTON  0x02
%define VK_MBUTTON  0x04
%define VK_BACK     0x08
%define VK_TAB      0x09
%define VK_RETURN   0x0D
%define VK_SHIFT    0x10
%define VK_CONTROL  0x11
%define VK_MENU     0x12
%define VK_PAUSE    0x13
%define VK_CAPITAL  0x14
%define VK_ESCAPE   0x1B
%define VK_SPACE    0x20
%define VK_PRIOR    0x21   ; Page Up
%define VK_NEXT     0x22   ; Page Down
%define VK_END      0x23
%define VK_HOME     0x24
%define VK_LEFT     0x25
%define VK_UP       0x26
%define VK_RIGHT    0x27
%define VK_DOWN     0x28
%define VK_INSERT   0x2D
%define VK_DELETE   0x2E

%define VK_0        0x30
%define VK_1        0x31
%define VK_2        0x32
%define VK_3        0x33
%define VK_A        0x41
%define VK_B        0x42
%define VK_C        0x43
%define VK_D        0x44
%define VK_E        0x45
%define VK_F        0x46
%define VK_G        0x47
%define VK_H        0x48
%define VK_Q        0x51
%define VK_R        0x52
%define VK_S        0x53
%define VK_T        0x54
%define VK_V        0x56
%define VK_W        0x57
%define VK_X        0x58
%define VK_Y        0x59
%define VK_Z        0x5A

%define KEY_REPEAT_FLAG 0x40000000

%endif